### ISSUE TITLE
Error in Progressbar arguments

### ISSUE THREAD

**Issue by PumpkinPai** [panzergame/gcodesender#2]
Hello, great bit of elegant software.  I'm able to connect to the machine fine, homing and moving with the console.  However, when I proceed to run the gcode file, I get this error:

```Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/gcodesender/src/gcodesender/__main__.py", line 42, in <module>
    controller.send_file(args.filename)
  File "/home/pi/gcodesender/src/gcodesender/grbl/controller.py", line 29, in send_file
    with progressbar.ProgressBar(max_value=total_lines, redirect_stdout=True) as bar:
TypeError: __init__() got an unexpected keyword argument 'max_value'
```

**Comment by panzergame** [comment]
Hello, thanks for your use.
Is the issue solved if you try to install progressbar2 python package ?
```
pip install progressbar2
```

If so I will fix this miss in the requirements.txt
